### ISSUE TITLE
Create loop on demand

### ISSUE THREAD

**Issue by japheth-waswa** [Cleveroad/LoopBar#25]
Is it possible to only loop items if they exceed screen size.ie
%%1.0%%
2 menu items should not be looped as they do not cover the entire screen size ie 1item to be aligned left & the other aligned right.
%%2.0%%
In most cases of you have 5 menu items then looping should be enable automatically

Can this be possible with the library ?

**Comment by ValeryGes** [comment]
Hi, @japheth-waswa, 

Thank you for your question and for using our library. 

There is an automatic scrolling mode in library. It can be enabled with attribute "enls_scrollMode". Just set it ti "auto" in your xml. In this mode it enable looping only if all items not fit the screen. 

But we not align items to right or to left, cause we don't think it will be looking well enough (because of selector items will look randomly scattered at tablets and large screens in this case for example). 
So if you think in your case it will look fine feel free to modify our library in your way.

With best regards, Cleveroad team.

**Comment by japheth-waswa** [comment]
Thanks i understand.
